name: Build astrovision documentation

on:
  push:
    branches:
      - 'main'
    tags:
      - "*"
  workflow_dispatch:

jobs:
  doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install docs dependencies
      run: |
        poetry install --only docs
    - name: Build documentation
      run: poetry run make html --directory docs/
    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/
        force_orphan: true
