name: Test astrovision package code

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  flake8:
    name: Run flake8 check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements/tests.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics

  pytest:
    name: Test package code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install numpy
      run: |
        pip install --upgrade pip
        pip install numpy
    - name: Install GDAL
      run: |
        ./install_gdal.sh
    - name: Install dependencies
      run: |
        pip install -r requirements/tests.txt -r requirements/required.txt
    - name: Install astrovision package
      run: |
        pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
